[package]
name = "frame-remote-externalities"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "An externalities provided environment that can load itself from remote nodes or cached files"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16", features = ["http-client"] }
codec = { package = "parity-scale-codec", version = "3.4.0" }
log = "0.4"
serde = "1"
frame-support = { version = "4.0.0-dev", optional = true, path = "../../../frame/support" }
sp-core = { version = "7", path = "../../../primitives/core" }
sp-io = { version = "7", path = "../../../primitives/io" }
sp-runtime = { version = "7", path = "../../../primitives/runtime" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
substrate-rpc-client = { path = "../rpc/client" }
futures = "0.3"
async-recursion = "1.0.4"

[dev-dependencies]
frame-support = { version = "4.0.0-dev", path = "../../../frame/support" }
pallet-elections-phragmen = { version = "5.0.0-dev", path = "../../../frame/elections-phragmen" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
remote-test = ["frame-support"]
